'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import { Activity, AlertTriangle, Boxes, CalendarDays, CheckCircle2, ChevronDown, ClipboardList, Download, LayoutDashboard, LogOut, Menu, PackageCheck, Plus, Save, Search, Settings, SlidersHorizontal, Users, X } from 'lucide-react';
import { adjustInventory, createEventDay, exportParticipantsCsv, getAdminData, getEventDays, isDemoAdmin, saveEventDay, setDemoAdmin } from '@/lib/client-api';
import { getVietnamDate, type EventDate } from '@/lib/constants';
import { firebaseAuth, hasFirebaseConfig } from '@/lib/firebase-client';
import type { AdminData, EventDay, Participant } from '@/lib/types';

export function AdminLogin() {
  const router = useRouter(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  useEffect(() => {
    if (!hasFirebaseConfig) {
      if (isDemoAdmin()) router.replace('/bio-admin-9x32');
      return;
    }
    if (!firebaseAuth) return;
    return onAuthStateChanged(firebaseAuth, (user) => {
      if (user) router.replace('/bio-admin-9x32');
    });
  }, [router]);
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); setError(''); setLoading(true);
    try {
      if (hasFirebaseConfig && firebaseAuth) await signInWithEmailAndPassword(firebaseAuth,email,password); else setDemoAdmin(true);
      router.replace('/bio-admin-9x32');
    } catch { setError('Email hoặc mật khẩu chưa chính xác.'); }
    finally { setLoading(false); }
  };
  return <main className="admin-login-shell"><section className="login-card"><div className="admin-brand"><strong>BIODERMA</strong><span>SÉBIUM REBALANCE LAB</span></div><div className="login-icon"><ShieldAdmin /></div><h1>Đăng nhập CMS</h1><p>Quản lý người tham gia, tồn kho và mã xác nhận.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="admin@bioderma.vn" required /></label><label>Mật khẩu<input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} placeholder="••••••••" required /></label>{error && <p className="form-error">{error}</p>}<button className="admin-primary" disabled={loading}>{loading?'Đang đăng nhập...':'Đăng nhập'}</button></form>{!hasFirebaseConfig && <p className="demo-hint">Chế độ demo: nhập email và mật khẩu bất kỳ để xem CMS.</p>}</section></main>;
}

function ShieldAdmin() { return <Settings size={28} />; }

type Tab = 'overview'|'participants'|'inventory'|'settings';
const tabs: {id:Tab;label:string;icon:typeof LayoutDashboard}[] = [
  {id:'overview',label:'Tổng quan',icon:LayoutDashboard},{id:'participants',label:'Khách tham gia',icon:Users},{id:'inventory',label:'Tồn kho',icon:Boxes},{id:'settings',label:'Cấu hình',icon:Settings},
];

export function AdminDashboard() {
  const router=useRouter(); const [tab,setTab]=useState<Tab>('overview'); const [date,setDate]=useState<EventDate>(''); const [days,setDays]=useState<EventDay[]>([]); const [data,setData]=useState<AdminData|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [menu,setMenu]=useState(false); const [creating,setCreating]=useState(false);
  const load = async (selectedDate=date) => { if(!selectedDate)return;setLoading(true);setError('');try{setData(await getAdminData(selectedDate));}catch(err){if((err as Error).message.toLowerCase().includes('đăng nhập'))router.replace('/bio-admin-9x32/login');else setError((err as Error).message);}finally{setLoading(false);} };
  const refreshDays=async(preferredDate?:string)=>{setLoading(true);setError('');try{const list=await getEventDays();setDays(list);const today=getVietnamDate();const next=(preferredDate&&list.some(day=>day.date===preferredDate)?preferredDate:'')||(list.some(day=>day.date===today)?today:'')||(date&&list.some(day=>day.date===date)?date:'')||list.find(day=>day.date>=today)?.date||list.at(-1)?.date||'';setDate(next);if(!next){setData(null);setLoading(false);}else if(next===date)await load(next);}catch(err){setLoading(false);setError((err as Error).message);}};
  useEffect(()=>{
    if(!hasFirebaseConfig){if(!isDemoAdmin()){router.replace('/bio-admin-9x32/login');return;}queueMicrotask(()=>refreshDays());return;}
    if(!firebaseAuth){router.replace('/bio-admin-9x32/login');return;}
    return onAuthStateChanged(firebaseAuth,(user)=>{if(!user)router.replace('/bio-admin-9x32/login');else refreshDays();});
  },[]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(date)queueMicrotask(()=>load(date));},[date]); // eslint-disable-line react-hooks/exhaustive-deps
  const logout=async()=>{ if(firebaseAuth) await signOut(firebaseAuth); setDemoAdmin(false); router.replace('/bio-admin-9x32/login'); };
  const switchTab=(next:Tab)=>{setTab(next);setMenu(false);};
  return <main className="admin-shell">
    <aside className={`admin-sidebar ${menu?'open':''}`}><div className="admin-logo"><strong>BIODERMA</strong><span>EVENT CMS</span></div><button className="sidebar-close" onClick={()=>setMenu(false)} aria-label="Đóng menu"><X /></button><nav>{tabs.map(({id,label,icon:Icon})=><button key={id} className={tab===id?'active':''} onClick={()=>switchTab(id)}><Icon size={18}/>{label}</button>)}</nav><button className="logout-button" onClick={logout}><LogOut size={18}/>Đăng xuất</button></aside>
    {menu&&<button className="sidebar-overlay" onClick={()=>setMenu(false)} aria-label="Đóng menu"/>}
    <section className="admin-main"><header className="admin-topbar"><button className="menu-button" onClick={()=>setMenu(true)} aria-label="Mở menu"><Menu/></button><div><h1>{tabs.find((item)=>item.id===tab)?.label}</h1><p>Sébium Rebalance Lab · {days.length} ngày đã khởi tạo</p></div><div className="admin-topbar-actions"><label className="date-picker"><CalendarDays size={17}/><select value={date} onChange={(e)=>setDate(e.target.value)} disabled={!days.length}>{days.length?days.map((day)=><option key={day.date} value={day.date}>{day.label}</option>):<option>Chưa có ngày</option>}</select><ChevronDown size={15}/></label><button className="create-day-button" onClick={()=>setCreating(true)}><Plus size={16}/>Khởi tạo ngày</button></div></header>
      <div className="admin-content">{error&&<div className="admin-alert">{error}<button onClick={()=>date?load(date):refreshDays()}>Thử lại</button></div>}{loading?<div className="admin-loading">Đang tải dữ liệu...</div>:data?<>{tab==='overview'&&<Overview data={data}/>} {tab==='participants'&&<Participants data={data}/>} {tab==='inventory'&&<Inventory data={data} onChanged={()=>load(date)}/>} {tab==='settings'&&<DaySettings key={`${data.eventDay.date}-${data.eventDay.updatedAt || ''}`} day={data.eventDay} onChanged={()=>load(date)}/>}</>:<div className="admin-empty-day"><CalendarDays size={34}/><h2>Chưa có ngày hoạt động</h2><p>Khởi tạo ngày đầu tiên để bắt đầu quản lý tồn kho và thống kê.</p><button className="admin-primary" onClick={()=>setCreating(true)}><Plus size={16}/>Khởi tạo ngày</button></div>}</div>
    </section>
    {creating&&<CreateDayModal onClose={()=>setCreating(false)} onCreated={async(createdDate)=>{setCreating(false);await refreshDays(createdDate);}}/>}
  </main>;
}

function CreateDayModal({onClose,onCreated}:{onClose:()=>void;onCreated:(date:string)=>Promise<void>}){
  const [date,setDate]=useState(getVietnamDate());const [stock,setStock]=useState('');const [codes,setCodes]=useState({zone1:'',zone2:'',zone3:''});const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const selectedDate=String(new FormData(event.currentTarget).get('eventDate')||date);setError('');if(!/^\d{4}-\d{2}-\d{2}$/.test(selectedDate)){setError('Vui lòng chọn ngày hợp lệ.');return;}if(!Number.isInteger(Number(stock))||Number(stock)<0){setError('Tồn kho phải là số nguyên không âm.');return;}if(Object.values(codes).some(code=>!/^\d{4}$/.test(code))){setError('Mỗi mã zone phải gồm đúng 4 chữ số.');return;}setBusy(true);try{await createEventDay(selectedDate,Number(stock),codes);await onCreated(selectedDate);}catch(err){setError((err as Error).message);}finally{setBusy(false);}};
  return <div className="admin-modal-backdrop" role="presentation"><section className="admin-create-modal" role="dialog" aria-modal="true" aria-labelledby="create-day-title"><button className="modal-close" onClick={onClose} aria-label="Đóng"><X size={18}/></button><div className="panel-heading"><div><h2 id="create-day-title">Khởi tạo ngày hoạt động</h2><p>Tạo kho và mã xác nhận riêng cho một ngày.</p></div><CalendarDays size={21}/></div><form onSubmit={submit}><label>Ngày hoạt động<input name="eventDate" type="date" value={date} onChange={(event)=>setDate(event.target.value)} required/></label><label>Tồn kho đầu ngày<input type="number" min="0" step="1" value={stock} onChange={(event)=>setStock(event.target.value)} placeholder="Ví dụ: 500" required/></label><div className="code-settings">{([1,2,3] as const).map(zone=><label key={zone}>Mã Zone {zone}<input inputMode="numeric" maxLength={4} value={codes[`zone${zone}`]} onChange={(event)=>setCodes({...codes,[`zone${zone}`]:event.target.value.replace(/\D/g,'').slice(0,4)})} placeholder="4 chữ số" required/></label>)}</div>{error&&<p className="form-error">{error}</p>}<div className="create-day-actions"><button type="button" className="outline-action" onClick={onClose}>Hủy</button><button className="admin-primary" disabled={busy}>{busy?'Đang khởi tạo...':'Khởi tạo kho'}</button></div></form></section></div>;
}

function StatCard({label,value,note,icon:Icon,tone}:{label:string;value:number|string;note:string;icon:typeof Users;tone:string}) { return <article className={`stat-card ${tone}`}><div className="stat-icon"><Icon size={20}/></div><div><p>{label}</p><strong>{value}</strong><span>{note}</span></div></article>; }

function Overview({data}:{data:AdminData}) {
  const {participants,eventDay}=data;
  const z1=participants.filter(p=>p.currentZone>=1).length,z2=participants.filter(p=>p.currentZone>=2).length,z3=participants.filter(p=>p.currentZone>=3).length,consent=participants.filter(p=>p.consent).length;
  const women=participants.filter(p=>p.gender==='female').length,men=participants.length-women;
  return <>
    {eventDay.remainingStock<=20&&<div className={`inventory-warning ${eventDay.remainingStock===0?'danger':''}`}><AlertTriangle size={18}/><span>{eventDay.remainingStock===0?'Sample trong ngày đã hết.':`Tồn kho chỉ còn ${eventDay.remainingStock} sample.`}</span></div>}
    <section className="stats-grid"><StatCard label="Khách tham gia" value={participants.length} note={`${consent} đồng ý consent`} icon={Users} tone="blue"/><StatCard label="Hoàn thành Zone 2" value={z2} note={`${eventDay.distributedZone2} sample đã phát`} icon={PackageCheck} tone="green"/><StatCard label="Hoàn thành Zone 3" value={z3} note={`${eventDay.distributedZone3} sample đã phát`} icon={CheckCircle2} tone="purple"/><StatCard label="Tồn kho hiện tại" value={eventDay.remainingStock} note={`Tồn đầu ngày ${eventDay.openingStock}`} icon={Boxes} tone={eventDay.remainingStock<20?'orange':'teal'}/></section>
    <section className="admin-grid"><article className="admin-panel"><div className="panel-heading"><div><h2>Tiến độ trải nghiệm</h2><p>Số khách đã hoàn thành mỗi bước</p></div><Activity size={20}/></div><div className="progress-bars">{[["Đăng ký",participants.length],["Zone 1",z1],["Zone 2",z2],["Zone 3",z3]].map(([label,value])=><div key={String(label)}><span>{label}<strong>{value}</strong></span><div><i style={{width:`${participants.length?Number(value)/participants.length*100:0}%`}}/></div></div>)}</div></article><article className="admin-panel"><div className="panel-heading"><div><h2>Phân bổ sample</h2><p>Kho chung trong ngày</p></div><Boxes size={20}/></div><div className="stock-ring" style={{'--percent':`${eventDay.openingStock?eventDay.remainingStock/eventDay.openingStock*100:0}%`} as React.CSSProperties}><div><strong>{eventDay.remainingStock}</strong><span>còn lại</span></div></div><div className="stock-legend"><span><i className="z2"/>Zone 2: {eventDay.distributedZone2}</span><span><i className="z3"/>Zone 3: {eventDay.distributedZone3}</span></div></article><article className="admin-panel demographic-panel"><div className="panel-heading"><div><h2>Thông tin khách tham gia</h2><p>Phân bổ giới tính và độ tuổi trong ngày</p></div><Users size={20}/></div><div className="demographic-grid">{[['Nữ',women],['Nam',men],['18–24',participants.filter(p=>p.ageRange==='18-24').length],['25–45',participants.filter(p=>p.ageRange==='25-45').length],['Trên 45',participants.filter(p=>p.ageRange==='45+').length],['Không consent',participants.filter(p=>!p.consent).length]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div></article></section>
  </>;
}

function Participants({data}:{data:AdminData}) {
  const [search,setSearch]=useState(''); const [gender,setGender]=useState('all'); const [age,setAge]=useState('all'); const [progress,setProgress]=useState('all'); const [consent,setConsent]=useState('all'); const [sample,setSample]=useState('all');
  const filtered=useMemo(()=>data.participants.filter(p=>{const q=search.toLowerCase();const sampleMatch=sample==='all'||(sample==='z2'&&p.zone2SampleStatus==='received')||(sample==='z3'&&p.zone3SampleStatus==='received')||(sample==='out'&&(p.zone2SampleStatus==='out_of_stock'||p.zone3SampleStatus==='out_of_stock'));return(!q||p.publicCode.toLowerCase().includes(q)||(p.fullName||'').toLowerCase().includes(q)||(p.phone||'').includes(q))&&(gender==='all'||p.gender===gender)&&(age==='all'||p.ageRange===age)&&(consent==='all'||String(p.consent)===consent)&&(progress==='all'||p.currentZone===Number(progress))&&sampleMatch;}),[data.participants,search,gender,age,progress,consent,sample]);
  return <section className="admin-panel participant-panel"><div className="panel-heading"><div><h2>Danh sách khách hàng</h2><p>{filtered.length} trên {data.participants.length} khách</p></div><button className="outline-action" onClick={()=>exportParticipantsCsv(filtered)}><Download size={16}/>Xuất CSV</button></div><div className="filters"><label className="search-box"><Search size={16}/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Tìm mã, họ tên hoặc số điện thoại..."/></label><label><SlidersHorizontal size={15}/><select value={gender} onChange={(e)=>setGender(e.target.value)}><option value="all">Giới tính</option><option value="female">Nữ</option><option value="male">Nam</option></select></label><label><select value={age} onChange={(e)=>setAge(e.target.value)}><option value="all">Độ tuổi</option><option value="18-24">18–24</option><option value="25-45">25–45</option><option value="45+">Trên 45</option></select></label><label><select value={consent} onChange={(e)=>setConsent(e.target.value)}><option value="all">Consent</option><option value="true">Đồng ý</option><option value="false">Không đồng ý</option></select></label><label><select value={progress} onChange={(e)=>setProgress(e.target.value)}><option value="all">Tiến độ</option><option value="0">Chưa vào zone</option><option value="1">Zone 1</option><option value="2">Zone 2</option><option value="3">Zone 3</option></select></label><label><select value={sample} onChange={(e)=>setSample(e.target.value)}><option value="all">Trạng thái sample</option><option value="z2">Đã nhận tại Zone 2</option><option value="z3">Đã nhận tại Zone 3</option><option value="out">Gặp trạng thái hết hàng</option></select></label></div><div className="participant-table"><div className="table-row table-head"><span>Khách hàng</span><span>Thông tin</span><span>Tiến độ</span><span>Sample</span><span>Thời gian</span></div>{filtered.length?filtered.map(p=><ParticipantRow key={p.id} participant={p}/>):<div className="empty-state"><Users size={28}/><p>Chưa có khách phù hợp bộ lọc.</p></div>}</div></section>;
}

function ParticipantRow({participant:p}:{participant:Participant}) { return <div className="table-row"><span><strong>{p.fullName||'Khách không consent'}</strong><small>{p.publicCode}{p.phone?` · ${p.phone}`:''}</small></span><span><strong>{p.gender==='female'?'Nữ':'Nam'}{p.ageRange?` · ${p.ageRange}`:''}</strong><small>{p.consent?'Đồng ý consent':'Không consent'}</small></span><span><b className="progress-badge">Zone {p.currentZone}</b></span><span><small>Z2: {sampleLabel(p.zone2SampleStatus)}</small><small>Z3: {sampleLabel(p.zone3SampleStatus)}</small></span><span><strong>{new Date(p.createdAt).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}</strong><small>{new Date(p.createdAt).toLocaleDateString('vi-VN')}</small></span></div>; }
function sampleLabel(status?:string){return status==='received'?'Đã nhận':status==='out_of_stock'?'Hết hàng':'—';}

function Inventory({data,onChanged}:{data:AdminData;onChanged:()=>void}) {
  const [quantity,setQuantity]=useState(''); const [reason,setReason]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const day=data.eventDay;
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setBusy(true);try{await adjustInventory(day.date as EventDate,Number(quantity),reason);setQuantity('');setReason('');onChanged();}catch(err){setError((err as Error).message);}finally{setBusy(false);}};
  return <div className="admin-grid inventory-grid"><section className="admin-panel"><div className="panel-heading"><div><h2>Tồn kho trong ngày</h2><p>{day.label}</p></div><Boxes size={20}/></div><div className="inventory-summary"><div><span>Tồn đầu ngày</span><strong>{day.openingStock}</strong></div><div><span>Điều chỉnh</span><strong>{day.adjustments>0?'+':''}{day.adjustments}</strong></div><div><span>Đã phát</span><strong>{day.distributedZone2+day.distributedZone3}</strong></div><div className="remaining"><span>Còn lại</span><strong>{day.remainingStock}</strong></div></div><form className="adjust-form" onSubmit={submit}><h3>Điều chỉnh tồn kho</h3><p>Dùng số dương để nhập thêm, số âm để giảm kho.</p><label>Số lượng<input type="number" value={quantity} onChange={(e)=>setQuantity(e.target.value)} placeholder="Ví dụ: 20 hoặc -5" required/></label><label>Lý do<input value={reason} onChange={(e)=>setReason(e.target.value)} placeholder="Lý do điều chỉnh" required/></label>{error&&<p className="form-error">{error}</p>}<button className="admin-primary" disabled={busy||!quantity||!reason.trim()}>{busy?'Đang lưu...':'Lưu điều chỉnh'}</button></form></section><section className="admin-panel"><div className="panel-heading"><div><h2>Lịch sử kho</h2><p>Các giao dịch gần nhất</p></div><ClipboardList size={20}/></div><div className="ledger-list">{data.ledger.length?data.ledger.slice(0,30).map(item=><div key={item.id}><i className={item.quantity>0?'positive':'negative'}>{item.quantity>0?'+':''}{item.quantity}</i><span><strong>{item.type==='distribution'?`Phát sample Zone ${item.zone}`:'Điều chỉnh kho'}</strong><small>{item.reason||item.participantId||''}</small></span><time>{new Date(item.createdAt).toLocaleString('vi-VN')}</time></div>):<div className="empty-state"><ClipboardList size={28}/><p>Chưa có giao dịch.</p></div>}</div></section></div>;
}

function DaySettings({day,onChanged}:{day:EventDay;onChanged:()=>void}) {
  const [stock,setStock]=useState(String(day.openingStock));const [codes,setCodes]=useState(day.codes);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setMessage('');if(Object.values(codes).some(code=>!/^\d{4}$/.test(code))){setError('Mỗi mã zone phải gồm đúng 4 chữ số.');return;}setBusy(true);try{await saveEventDay(day.date as EventDate,Number(stock),codes);setMessage('Đã lưu cấu hình trong ngày.');onChanged();}catch(err){setError((err as Error).message);}finally{setBusy(false);}};
  return <section className="admin-panel settings-panel"><div className="panel-heading"><div><h2>Cấu hình {day.label}</h2><p>Thiết lập tồn đầu ngày và mã do PG cung cấp.</p></div><Settings size={20}/></div><form onSubmit={submit}><label>Tồn kho đầu ngày<input type="number" min="0" value={stock} onChange={(e)=>setStock(e.target.value)} required/></label><div className="code-settings">{([1,2,3] as const).map(zone=><label key={zone}>Mã Zone {zone}<input inputMode="numeric" maxLength={4} value={codes[`zone${zone}`]} onChange={(e)=>setCodes({...codes,[`zone${zone}`]:e.target.value.replace(/\D/g,'').slice(0,4)})} placeholder="4 chữ số" required/><small>Mã này dùng chung cho tất cả khách trong ngày.</small></label>)}</div><div className="settings-note"><Save size={18}/><p>Thay đổi mã có hiệu lực ngay. Khách đã hoàn thành zone không bị ảnh hưởng.</p></div>{error&&<p className="form-error">{error}</p>}{message&&<p className="success-message">{message}</p>}<button className="admin-primary" disabled={busy}>{busy?'Đang lưu...':'Lưu cấu hình'}</button></form></section>;
}
